---
- name: "Include roles for AWS servers"
  include_role:
    name: "{{ item }}"
  loop: "{{ ansible_local['awsroles']['default']['role'].split(',') }}"
  when: ansible_local['awsroles'] is defined
