---
- name: "Haproxy Setup check"
  shell: |
    if [ -e "/root/.setup/haproxy-rpms" ]
    then
      echo "true"
    else
      echo "false"
    fi
  register: initialsetup
  become: true

- name: "Block to perform initial setup"
  block:
    - name: "make setup tracking dir"
      file:
        path: /root/.setup
        state: directory
        mode: 0755

    - name: "Installing haproxy rpms"
      yum:
        name: ["haproxy"]
        state: latest

    - name: "make setup tracking dir"
      file:
        path: /root/.setup/haproxy-rpms
        state: touch
        mode: 0440
  when: initialsetup.stdout == "false"

- name: "Fixing haproxy config"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0600
  notify: restart haproxy

- name: "Set selinux flag to allow haproxy connections"
  shell: |
    semanage boolean --modify --on haproxy_connect_any

- name: "Enable and start haproxy"
  service:
    name: haproxy
    enabled: yes
    state: started
