---
- hosts: physical_servers
  tasks:
    - name: copying test script to host
      copy: src=leap_second_issue_detector.sh dest=/var/tmp/leap_second_issue_detector.sh mode=0755
    - name: running leap second issue detector
      shell:  /var/tmp/leap_second_issue_detector.sh
      register: result
    - name: forced failure when SUGGESTION detected
      shell: echo '{{ result.stdout }}' && /bin/false
      when: "'SUGGESTION' in result.stdout"
    - name: announce our results for logging
      debug: msg='{{ result.stdout }}'

