---
- include: "configure-osp-controllers.yml"
  when: osp_mode == 'controllers'

- include: "configure-osp-computes.yml"
  when: osp_mode == 'computes'

- include: "add-openstack-to-cfme.yml"
  when: cfme == 'true'
