---
- name: "Include distribution specific config"
  include: "{{ ansible_distribution }}.yml"

- name: "Include roles for AWS servers"
  include_role:
    name: "{{ ansible_local['awsroles']['default']['roles'] }}"
  when: ansible_local['awsroles'] is defined
