---
- include: ose-get-token.yml
- name: "Add Openstack provider to CFME"
  hosts: cloudforms.stack.maskedadmins.com
  vars:
    cfme_user: "admin"
    cfme_pass: "smartvm"
    cfme_server: "{{ ansible_hostname }}"
    cfme_project: redhat-lab
    osp10_name: "OSP10"
    osp10_server: compute4.maskedadmins.com
    osp10_security: non-ssl
    osp10_user: "dtaylor"
    osp10_pass: "redhat123"
  tasks:
    - name: "Use the API to add Openstack provider"
      shell: |
        curl -k --user {{ cfme_user }}:{{ cfme_pass }} \
        -i -X POST -H "Accept: application/json" \
        -d "{
              \"type\"      : \"ManageIQ::Providers::Openstack::CloudManager\",
              \"name\"      : \"{{ osp10_name }}\",
              \"hostname\"  : \"{{ osp10_server }}\",
              \"ipaddress\" : \"$(host {{ osp10_server }} | awk '{print $4}')\",
              \"security_protocol\"      : \"{{ osp10_security }}\",
              \"credentials\" : {
                \"userid\"   : \"{{ osp10_user }}\",
                \"password\" : \"{{ osp10_pass }}\"
              }
        }" \
        https://{{ cfme_server }}/api/providers
