---
- name: "Add Tower provider to CFME"
  hosts: tower.stack.maskedadmins.com
  vars:
    cfme_user: "admin"
    cfme_pass: "smartvm"
    cfme_creds: "admin:smartvm"
    cfme_type: "ManageIQ::Providers::AnsibleTower::Provider"
    cfme_server: "cloudforms.stack.maskedadmins.com"
    cfme_project: redhat-lab
    tower_name: "Ansible Tower"
    tower_server: "tower.stack.maskedadmins.com"
    tower_security: ssl
    tower_user: "admin"
    tower_user: "ansible"
  tasks:
    - name: "Add Tower provider"
      shell: |
        curl -k --user {{ cfme_creds }} \
        -i -X POST -H "Accept: application/json" \
        -d '{
              "type"      : "{{ cfme_type }}",
              "name"      : "{{ tower_name }}",
              "hostname"  : "{{ tower_server }}",
              "security_protocol"      : "{{ tower_security }}",
              "credentials" : {
                "userid"   : "{{ tower_user }}",
                "password" : "{{ tower_pass }}"
              }' \
        https://{{ cfme_server }}/api/providers
