---
- include: ose-get-token.yml
- name: "Add Openshift provider to CFME"
  hosts: ose-cluster-master.stack.maskedadmins.com
  vars:
    cfme_user: "admin"
    cfme_pass: "smartvm"
    cfme_creds: "admin:smartvm"
    cfme_type: "ManageIQ::Providers::Openshift::ContainerManager"
    cfme_server: "cloudforms.stack.maskedadmins.com"
    cfme_project: redhat-lab
    ose_name: "OSE3-3"
    ose_server: "ose-cluster-master.stack.maskedadmins.com"
    ose_security: ssl
    ose_user: "admin"
  tasks:
    - name: "Add Openshift provider using the token acquired earlier"
      shell: |
        curl -k --user {{ cfme_creds }} \
        -i -X POST -H "Accept: application/json" \
        -d '{
              "type"      : "{{ cfme_type }}",
              "name"      : "{{ ose_name }}",
              "hostname"  : "{{ ose_server }}",
              "security_protocol"      : "{{ ose_security }}",
              "credentials" : {
                "userid"   : "{{ ose_user }}",
                "password" : "{{ ose_token }}"
              }' \
        https://{{ cfme_server }}/api/providers
