---
- name: "Customize OSP 10 -  compute nodes"
  hosts: osp10-computes
  vars:
    openstack:
      project_name: Redhat_Lab
      project_user: dtaylor
      project_pass: redhat123
      dns_server: 10.55.102.5
      dhcp_server: 10.55.102.5
      dhcp_domain: stack.maskedadmins.com
      dhcp_mtu: 1454
      cpupinning:
        use: "yes"
        device: /dev/sda
      hugepages:
        use: "yes"
        device: /dev/sda
      glance:
        mount_nfs: "yes"
        import: "yes"
        image_path: /mnt/compute1/glance-images
        nfs_target: 10.55.2.155:/mnt/drobo/software/BackUp/openstack/glance-images
        image_names: ['PXE-client-bare.raw','cfme-rhos-5.8.0.17-1.x86_64.qcow2','RHEL-7.3-Cloud-bare.qcow2','RHEL-Atomic-7.2.6-1-bare.qcow2','QCI-Template-bare.qcow2']
      networks:
        Provisioning_102:
          cidr: 10.55.102.0/24
          vlanid: 102
          subnet_name: NET102
          dhcp_start: 10.55.102.200
          dhcp_end: 10.55.102.225
          gateway: 10.55.102.1
        Storage_105:
          cidr: 10.55.105.0/24
          vlanid: 105
          subnet_name: NET105
          dhcp_start: 10.55.105.200
          dhcp_end: 10.55.105.225
          gateway: 10.55.105.1
  tasks:
    - name: "Configure compute nodes for Huge Pages"
      shell: |
        grubby --update-kernel=ALL --args="hugepagesz=2M hugepages=2048"
        grub2-install {{ openstack['hugepages']['device'] }}
        echo 'vm.nr_hugepages=6144' >> /etc/sysctl.conf
      args:
        chdir: /root
      become: true
      when: openstack['hugepages']['use']  == "yes"
      #ignore_errors: yes

    - name: "Installing numactl"
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "numactl"
      become: true
      when: openstack['cpupinning']['use']  == "yes"

    - name: get the guest cpus we isolate for guest images
      shell: |
        numactl --hardware | grep 'node 0 cpus' | cut -d\: -f2| sed -e 's/ 0 1 //g' | sed -e 's/ /,/g'
      become: true
      register: guestcpus
      when: openstack['cpupinning']['use']  == "yes"

    - name: update nova.conf cpu pinning values
      lineinfile:
        line: "vcpu_pin_set={{ guestcpus.stdout }}"
        dest: /etc/nova/nova.conf
        regexp: "^vcpu_pin_set=*"
        state: present
      when: openstack['cpupinning']['use']  == "yes"

    - name: "Configure the system for cpu pinning"
      shell: |
        grubby --update-kernel=ALL --args="isolcpus={{ guestcpus.stdout }}"
        grub2-install {{ openstack['cpupinning']['device'] }}
      args:
        chdir: /root
      become: true
      when: openstack['cpupinning']['use']  == "yes"
      #ignore_errors: yes

    - name: update nova.conf domain values
      lineinfile:
        line: "dhcp_domain={{ openstack['dhcp_domain'] }}"
        dest: /etc/nova/nova.conf
        regexp: "^dhcp_domain=*"
        state: present

    - name: "Enabling and restarting services openstack nova "
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - openstack-nova-compute
      become: true

    - name: "Reboot to new settings. Back in 10 mins or so"
      shell: |
        shutdown -r +2 && sleep 2
      args:
        chdir: /root
      become: true
      when: ( openstack['hugepages']['use']  == "yes" ) or ( openstack['cpupinning']['use']  == "yes" )
