---
- include: firstboot.yml
- name: "Configure Cloudforms Management Engine"
  hosts: all
  vars:
    cfme_user: "root"
    cfme_pass: "smartvm"
    cfme_project: redhat-lab
  tasks:
    - name: "Configure CFME"
      shell: |
        appliance_console_cli -v --internal --dbdisk /dev/vdb --region 0 --password {{ cfme_pass }}
      become: true
