---
- name: Firstboot configuration tasks
  hosts: all
  vars:
    dns_domain: "maskedadmins.com"
    #current patch level enforced by redhat insights job
    host_config_server: "10.55.102.248"
    redhat_insights_key: ""
    redhat_insights_jobid: ""
    sat6:
      url: "satellite-6-demo-in-osp8.stack.maskedadmins.com"
      #url: "10.55.102.204"
      user: "admin"
      pass: "redhat123"
      org: Redhat_Lab
      hostgroup: "RHEL_7_x86_64_Hostgroup for stack.maskedadmins.com 2"
      location: "Private_Cloud"
      environment: "Development"
      activation_key: "Redhat_Lab-Development-key"
  tasks:
    - include: "firstboot/{{ ansible_distribution }}.yml"

## Commented out to demo in the Ansible Tower
#- name: "Bring system to current patch level"
#  hosts: all
#  tasks:
#    - name: "Run Security Update Job"
#      shell: |
#         curl -k --data 'host_config_key={{ redhat_insights_key }}' https://{{ host_config_server }}:443/api/v1/job_templates/{{ redhat_insights_jobid }}/callback/"

## copy over the dynatrace monitoring installation and run it
- include: "install-dynatrace.yml"


## playbook to install OSP 10 on physical nodes on firstboot
## inventory hardcoded to the compute nodes
- include: "rhel-demo-poweron-install-openstack.yml"
## playbook to install OSE on nodes
## inventory hardcoded to the ose nodes
- include: "configure-ose-nodes.yml"

- include: "install-redhat-insights.yml"
