---
- name: Firstboot configuration tasks
  hosts: all
  vars:
    dns_domain: "maskedadmins.com"
  tasks:
    - include: "firstboot/{{ ansible_distribution }}.yml"

## Commented out to demo in the Ansible Tower
#    - name: "Run Security Update Job"
#      shell: "curl -k --data 'host_config_key={{ redhat_insights_key }}' https://{{ host_config_server }}:443/api/v1/job_templates/{{ redhat_insights_jobid }}/callback/"

## playbook to install OSP 10 on physical nodes on firstboot
- include: "rhel-demo-poweron-install-openstack.yml"
