---
- name: Firstboot configuration tasks
  hosts: all
  vars:
    dns_domain: "maskedadmins.com"
    #current patch level enforced by redhat insights job
    host_config_server: "10.55.102.248"
    redhat_insights_key: ""
    redhat_insights_jobid: ""
  tasks:
    - include: "firstboot/{{ ansible_distribution }}.yml"

## Commented out to demo in the Ansible Tower
#- name: "Bring system to current patch level"
#  hosts: all
#  tasks:
#    - name: "Run Security Update Job"
#      shell: |
#         curl -k --data 'host_config_key={{ redhat_insights_key }}' https://{{ host_config_server }}:443/api/v1/job_templates/{{ redhat_insights_jobid }}/callback/"

## copy over the dynatrace install script
- name: "Install Dynatrace Monitoring Agent"
  hosts: all
  tasks:
    - name: "Copy over Dynatrace script"
      copy:
        dest: /opt/Dynatrace-OneAgent-Linux-1.121.186.sh
        src: "/opt/Dynatrace-OneAgent-Linux-1.121.186.sh"
        owner: root
        group: root
        mode: 0755

    - name: "Running Dynatrace script"
      shell: |
        echo "Running Dynatrace script"
        /opt/Dynatrace-OneAgent-Linux-1.121.186.sh
      args:
        chdir: /opt


## playbook to install OSP 10 on physical nodes on firstboot
## inventory hardcoded to the compute nodes
- include: "rhel-demo-poweron-install-openstack.yml"
