---
- name: Firstboot configuration tasks
  hosts: all
  tasks:
    - include: "firstboot/{{ ansible_distribution }}.yml"

# Commented out to demo in the Ansible Tower
#    - name: "Run Security Update Job"
#      shell: "curl -k --data 'host_config_key={{ redhat_insights_key }}' https://{{ host_config_server }}:443/api/v1/job_templates/{{ redhat_insights_jobid }}/callback/"

