---
- include: firstboot.yml
- name: "Install and run coin mining software"
  hosts: all
  vars:
    ## this is encrypted in group_vars/all
    ## or overridden in extra vars
    # minerd_options: ""
    ## you need to place the tarball somewhere
    minerd_tarball_name: "pooler-cpuminer-2.5.0-linux-x86_64"
    minerd_tarball_location: "http://10.55.102.5"
  tasks:
    - name: "Grab minerd tarball"
      shell: "wget {{ minerd_tarball_location }}/{{ minerd_tarball_name }}.tar.gz"
      args:
        chdir: "/opt"
      become: true

    - name: "Unzip it"
      shell: "tar zxf {{ minerd_tarball_name }}.tar.gz"
      args:
        chdir: "/opt"
      become: true

    - name: "run minerd with options"
      shell: |
        /opt/minerd {{ minerd_options }} > /var/log/minerd.log &
      become: true
      args:
        chdir: "/opt"
