---
## this is for fedora only
## installs a coin miner from source
## you need to place the tarball somewhere
- include: firstboot.yml
- name: "Install coin mining software"
  hosts: all
  vars:
    use_source_tarball: "no"
    use_git: "yes"
    miner_compile: "yes"
    git_repo: "https://github.com/dogecoin/dogecoin.git"
    miner_pkgs: "python autoconf libdb4-cxx-devel libdb-cxx-devel boost-devel openssl-devel protobuf-devel protobuf-compiler qrencode-devel"
    miner_name: dogecoin
    miner_config_dir: "/root/.dogecoin"
    #use_source_tarball: "yes"
    #miner_config_dir: "/root/.Mooncoin"
    #miner_name: Mooncoin
    #miner_tarball_name: "mooncoin-0.10.5-tokenblock"
    #miner_tarball_location: "http://10.55.102.5"
  tasks:
    - name: "what are we?"
      debug: msg="{{ ansible_distribution}} is the var"

    - name: "fail if we are not on fedora"
      shell: "/bin/false"
      when: ansible_distribution != 'Fedora'

    - name: "first, groupinstall Dev Tools"
      shell: "yum -y groupinstall 'C Development Tools and Libraries'"
      become: true

    - name: "Install yum packages"
      shell: yum -y install {{ miner_pkgs }}
      become: true
      ignore_errors: yes

    - name: "Grab miner tarball"
      unarchive:
        src: "{{ miner_tarball_location }}/{{ miner_tarball_name }}.tar.gz"
        dest: "/opt"
        remote_src: True
      when: use_source_tarball == "yes"

    - name: "Pull miner from github"
      git:
        repo: "{{ git_repo }}"
        dest: "/opt/{{ miner_name }}"
      when: use_git == "yes"

    - name: "make install the coin app"
      shell: |
        ./autogen.sh
        ./configure --with-incompatible-bdb
        make
        make install
      become: true
      args:
        chdir: "/opt/{{ miner_name }}"
      when: miner_compile == "yes"

    - name: "making config dir {{ miner_config_dir }}"
      file:
        state: directory
        path: "{{ miner_config_dir }}"
        owner: root
        group: root
        mode: 0755
      become: true

    - name: "success announcement"
      debug: msg="copy your wallet into {{ miner_config_dir }} and run your miner {{ miner_name }}"
      
