---
- include: firstboot.yml
# Launches new OSE 3.3 instance with provisioning userdata using Cloud-Init
- name: install ansible tower
  hosts: all
  tasks:
    - name: "Install yum packages"
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ tower_packages }}"
      become: true

    - name: "Grab tower tarball"
      unarchive:
        src: "{{ tower_tarball_location }}"
        dest: /opt
        remote_src: True

    - name: "Change the inventory passwords to 'ansible' for installation"
      shell: |
        cd ansible-tower-setup-*
        sed -i -e "s/admin_password=''/admin_password='ansible'/g" inventory
        sed -i -e "s/redis_password=''/redis_password='ansible'/g" inventory
        sed -i -e "s/pg_password=''/pg_password='ansible'/g" inventory
        sed -i -e "s/rabbitmq_password=''/rabbitmq_password='ansible'/g" inventory
      args:
        chdir: /opt

    - name: "Install Ansible Tower"
      shell: |
        cd ansible-tower-setup-*
        ./setup.sh
      args:
        chdir: /opt
      become: true
