---
## this is for fedora only
## installs a coin miner from source
## you need to place the tarball somewhere
- name: "Install coin mining software"
  hosts: all
  tasks:
    - name: "what are we?"
      debug: msg="{{ ansible_distribution}} is the var"

    - name: "fail if we are not on fedora"
      shell: "/bin/false"
      when: ansible_distribution != 'Fedora'

    - name: "first, groupinstall Dev Tools"
      shell: "yum -y groupinstall 'C Development Tools and Libraries'"
      become: true

    - name: "Install yum packages"
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ miner_pkgs }}"
      become: true
      ignore_errors: yes
    - name: "Grab tower tarball"
      unarchive:
        src: "{{ miner_tarball_location }}/{{ miner_tarball_name }}.tar.gz"
        dest: "/opt"
        remote_src: True

    - name: "make install the coin app"
      shell: |
        ./autogen.sh
        ./configure
        make
        make install
      become: true
      args:
        chdir: "/opt/{{ miner_tarball_name }}"

    - name: "making config dir {{ miner_config_dir }}"
      file:
        state: directory
        path: "{{ miner_config_dir }}"
        owner: root
        group: root
        mode: 0755
      become: true

    - name: "success announcement"
      debug: msg="copy your wallet into {{ miner_config_dir }} and run your miner {{ miner_name }}"
      
