---
## copy over the dynatrace install script
- name: "Install Dynatrace Monitoring Agent for Linux"
  hosts: all
  tasks:
    - name: "Copy over Dynatrace script"
      copy:
        dest: /opt/Dynatrace-OneAgent-Linux-1.121.186.sh
        src: "/opt/Dynatrace-OneAgent-Linux-1.121.186.sh"
        owner: root
        group: root
        mode: 0755

    - name: "Running Dynatrace script"
      shell: |
        /opt/Dynatrace-OneAgent-Linux-1.121.186.sh
      args:
        chdir: /opt

    - name: "Updating Dynatrace config to allow access to log files"
      lineinfile: 
        line: "AppLogContentAccess=true"
        dest: /var/lib/dynatrace/oneagent/agent/config/ruxitagentloganalytics.conf
        regexp: "^AppLogContentAccess=false$"
        state: present

