---
- name: "Update inventory"
  gather_facts: no
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "update all the ansible tower osp10 repos"
      shell: |
        curl --ciphers ecdhe_rsa_aes_128_gcm_sha_256 -f -k \
        -H 'Content-Type: application/json' -XPOST \
        --user admin:ansible \
        https://{{ default_tower_server }}/api/v2/inventories/{{ item }}/update_inventory_sources/
        sleep 5
      with_items:
        - 3
      ignore_errors: yes
