---
- name: "Update inventory"
  gather_facts: no
  hosts: sat6*
  become: true
  tasks:
    - name: "Updating inventories"
      uri:
        url: "https://{{ default_tower_server }}/api/v2/inventories/{{ item.id }}/update_inventory_sources/"
        validate_certs: no
        method: POST
        status_code: 201
        user: admin
        password: ansible
        headers:
          Content-Type: "application/json"
      delay: 120
      with_items:
        - name: 'Openstack Inventory'
          id: '3'
      ignore_errors: yes
      delegate_to: localhost
