---
- name: "Grab an OSE authorization token"
  hosts: ose-cluster-master.stack.maskedadmins.com
  vars:
    ose_user: "admin"
    ose_pass: "redhat123"
    ose_project: redhat-lab
  tasks:
    - name: "Log into OSE"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }} > /dev/null 2>&1
        oc whoami -t
      register: token
      become: true
    
    - name: "Display OSE authorization token"
      debug: var=token
