---
- name: "Scale an Openshift app to the desired size"
  hosts: all
  vars:
    ose:
      app: "simplephp"
      user: "admin"
      pass: "redhat123"
      project: Redhat_Lab
      replicas: 3
  tasks:
    - name: "Scale {{ ose['app'] }} to {{ ose['replicas'] }} replicas"
      shell: |
        oc login -u {{ ose['user'] }} -p {{ ose['pass'] }} -n {{ ose['project'] }}
        oc scale dc {{ ose['app'] }} --replicas={{ ose['replicas'] }}
