---
- include: "ose-get-token.yml"
- name: "Launch ISPconfig"
  hosts: ose-cluster-master*
  vars:
    ose_project: "redhat-lab"
    ose_user: "admin"
    ose_pass: "redhat123"
    github_url: "https://github.com/syspimp/docker-ispconfig.git"
    ispconfig_container: "docker-ispconfig"
  tasks:
#    - name: "Pull custom configuration from github"
#      git:
#        repo: "{{ github_url }}"
#        dest: "/opt/{{ ispconfig_container }}"
#
#    - name: "Build and push {{ ispconfig_container }} container"
#      shell: |
#        docker build --no-cache -t {{ ispconfig_container }} .
#        oc login -u {{ ose_user }} -p {{ ose_pass }}
#        oc project default
#        server=$(oc get svc|grep docker-reg| awk '{print $2}')
#        id=$(docker images|grep ^{{ ispconfig_container }}|awk '{print $3}')
#        token=$(oc whoami -t)
#        docker login -u {{ ose_user }} -p $token ${server}:5000
#        docker tag {{ ispconfig_container }} ${server}:5000/{{ ose_project }}/{{ ispconfig_container }}
#        docker push ${server}:5000/{{ ose_project }}/{{ ispconfig_container }}
#      args:
#        chdir: "/opt/{{ ispconfig_container }}"
#      become: true

    - name: "create template for volume claims"
      template:
        src: ose/ispconfig-volume-claims.yml.j2
        dest: /tmp/ispconfig-volume-claims.yml
        mode: 0644
        owner: root
        group: root

    - name: "create template for volume"
      template:
        src: ose/ispconfig-volumes.yml.j2
        dest: /tmp/ispconfig-volumes.yml
        mode: 0644
        owner: root
        group: root

    - name: "Create volume claims via oc binary"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        oc create -f /tmp/ispconfig-volumes.yml
      become: true

    - name: "Create volume claims via oc binary"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        sed -e 's/REPLACEME/{{ item }}/' /tmp/ispconfig-volume-claims.yml | oc create -f -
      become: true
      with_items:
        - www
        - mail
        - mysql
        - backup
        - data
        - log

    - name: "Build and push {{ ispconfig_container }} container"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        oc new-app {{ github_url }}
      become: true
#
#    - name: "Create ISPConfig Pod"
#      oc:
#        host: ose-cluster-master.dev.maskedadmins.com
#        namespace: "{{ ose_project }}"
#        state: present
#        inline:
#          apiVersion: v1
#          items:
#          - apiVersion: v1
#            kind: ImageStream
#            metadata:
#              annotations:
#                openshift.io/generated-by: OpenShiftNewApp
#              creationTimestamp: null
#              labels:
#                app: docker-ispconfig
#              name: debian
#            spec:
#              tags:
#              - annotations:
#                  openshift.io/imported-from: debian:jessie
#                from:
#                  kind: DockerImage
#                  name: debian:jessie
#                generation: null
#                importPolicy: {}
#                name: jessie
#                referencePolicy:
#                  type: ""
#            status:
#              dockerImageRepository: ""
#          - apiVersion: v1
#            kind: ImageStream
#            metadata:
#              annotations:
#                openshift.io/generated-by: OpenShiftNewApp
#              creationTimestamp: null
#              labels:
#                app: docker-ispconfig
#              name: docker-ispconfig
#            spec: {}
#            status:
#              dockerImageRepository: ""
#          - apiVersion: v1
#            kind: BuildConfig
#            metadata:
#              annotations:
#                openshift.io/generated-by: OpenShiftNewApp
#              creationTimestamp: null
#              labels:
#                app: docker-ispconfig
#              name: docker-ispconfig
#            spec:
#              nodeSelector: null
#              output:
#                to:
#                  kind: ImageStreamTag
#                  name: docker-ispconfig:latest
#              postCommit: {}
#              resources: {}
#              source:
#                git:
#                  uri: https://github.com/syspimp/docker-ispconfig
#                type: Git
#              strategy:
#                dockerStrategy:
#                  from:
#                    kind: ImageStreamTag
#                    name: debian:jessie
#                type: Docker
#              triggers:
#              - github:
#                  secret: T4NtTXAgOiirkUnyQfmy
#                type: GitHub
#              - generic:
#                  secret: AkSaLb8Nikm6dVjro-dr
#                type: Generic
#              - type: ConfigChange
#              - imageChange: {}
#                type: ImageChange
#            status:
#              lastVersion: 0
#          - apiVersion: v1
#            kind: DeploymentConfig
#            metadata:
#              annotations:
#                openshift.io/generated-by: OpenShiftNewApp
#              creationTimestamp: null
#              labels:
#                app: docker-ispconfig
#              name: docker-ispconfig
#            spec:
#              replicas: 1
#              selector:
#                app: docker-ispconfig
#                deploymentconfig: docker-ispconfig
#              strategy:
#                resources: {}
#              template:
#                metadata:
#                  annotations:
#                    openshift.io/generated-by: OpenShiftNewApp
#                  creationTimestamp: null
#                  labels:
#                    app: docker-ispconfig
#                    deploymentconfig: docker-ispconfig
#                spec:
#                  containers:
#                  - image: docker-ispconfig:latest
#                    name: docker-ispconfig
#                    ports:
#                    - containerPort: 30003
#                      protocol: TCP
#                    - containerPort: 30006
#                      protocol: TCP
#                    - containerPort: 953
#                      protocol: TCP
#                    - containerPort: 30001
#                      protocol: TCP
#                    - containerPort: 22
#                      protocol: TCP
#                    - containerPort: 53
#                      protocol: TCP
#                    - containerPort: 80
#                      protocol: TCP
#                    - containerPort: 8080
#                      protocol: TCP
#                    - containerPort: 30000
#                      protocol: TCP
#                    - containerPort: 30008
#                      protocol: TCP
#                    - containerPort: 20
#                      protocol: TCP
#                    - containerPort: 21
#                      protocol: TCP
#                    - containerPort: 30005
#                      protocol: TCP
#                    - containerPort: 3306
#                      protocol: TCP
#                    - containerPort: 443
#                      protocol: TCP
#                    - containerPort: 30002
#                      protocol: TCP
#                    - containerPort: 30009
#                      protocol: TCP
#                    - containerPort: 30004
#                      protocol: TCP
#                    - containerPort: 30007
#                      protocol: TCP
#                    resources: {}
#                    volumeMounts:
#                      -
#                        mountPath: "/var/www"
#                        name: "www"
#                      -
#                        mountPath: "/etc"
#                        name: "etc"
#                      -
#                        mountPath: "/var/mail"
#                        name: "mail"
#                      -
#                        mountPath: "/var/backup"
#                        name: "backup"
#                      -
#                        mountPath: "/var/lib/mysql"
#                        name: "mysql"
#                      -
#                        mountPath: "/usr/local/ispconfig"
#                        name: "data"
#                      -
#                        mountPath: "/var/log"
#                        name: "log"
#                    volumes:
#                      -
#                        name: "www"
#                        persistentVolumeClaim:
#                          claimName: "ispconfig-www"
#                      -
#                        name: "etc"
#                        persistentVolumeClaim:
#                          claimName: "ispconfig-etc"
#                      -
#                        name: "mail"
#                        persistentVolumeClaim:
#                          claimName: "ispconfig-mail"
#                      -
#                        name: "backup"
#                        persistentVolumeClaim:
#                          claimName: "ispconfig-backup"
#                      -
#                        name: "mysql"
#                        persistentVolumeClaim:
#                          claimName: "ispconfig-mysql"
#                      -
#                        name: "data"
#                        persistentVolumeClaim:
#                          claimName: "ispconfig-data"
#                      -
#                        name: "log"
#                        persistentVolumeClaim:
#                          claimName: "ispconfig-log"
#    
#              test: false
#              triggers:
#              - type: ConfigChange
#              - imageChangeParams:
#                  automatic: true
#                  containerNames:
#                  - docker-ispconfig
#                  from:
#                    kind: ImageStreamTag
#                    name: docker-ispconfig:latest
#                type: ImageChange
#            status:
#              availableReplicas: 0
#              latestVersion: 0
#              observedGeneration: 0
#              replicas: 0
#              unavailableReplicas: 0
#              updatedReplicas: 0
#          - apiVersion: v1
#            kind: Service
#            metadata:
#              annotations:
#                openshift.io/generated-by: OpenShiftNewApp
#              creationTimestamp: null
#              labels:
#                app: docker-ispconfig
#              name: docker-ispconfig
#            spec:
#              ports:
#              - name: 20-tcp
#                port: 20
#                protocol: TCP
#                targetPort: 20
#              - name: 21-tcp
#                port: 21
#                protocol: TCP
#                targetPort: 21
#              - name: 22-tcp
#                port: 22
#                protocol: TCP
#                targetPort: 22
#              - name: 53-tcp
#                port: 53
#                protocol: TCP
#                targetPort: 53
#              - name: 80-tcp
#                port: 80
#                protocol: TCP
#                targetPort: 80
#              - name: 443-tcp
#                port: 443
#                protocol: TCP
#                targetPort: 443
#              - name: 953-tcp
#                port: 953
#                protocol: TCP
#                targetPort: 953
#              - name: 3306-tcp
#                port: 3306
#                protocol: TCP
#                targetPort: 3306
#              - name: 8080-tcp
#                port: 8080
#                protocol: TCP
#                targetPort: 8080
#              - name: 30000-tcp
#                port: 30000
#                protocol: TCP
#                targetPort: 30000
#              - name: 30001-tcp
#                port: 30001
#                protocol: TCP
#                targetPort: 30001
#              - name: 30002-tcp
#                port: 30002
#                protocol: TCP
#                targetPort: 30002
#              - name: 30003-tcp
#                port: 30003
#                protocol: TCP
#                targetPort: 30003
#              - name: 30004-tcp
#                port: 30004
#                protocol: TCP
#                targetPort: 30004
#              - name: 30005-tcp
#                port: 30005
#                protocol: TCP
#                targetPort: 30005
#              - name: 30006-tcp
#                port: 30006
#                protocol: TCP
#                targetPort: 30006
#              - name: 30007-tcp
#                port: 30007
#                protocol: TCP
#                targetPort: 30007
#              - name: 30008-tcp
#                port: 30008
#                protocol: TCP
#                targetPort: 30008
#              - name: 30009-tcp
#                port: 30009
#                protocol: TCP
#                targetPort: 30009
#              selector:
#                app: docker-ispconfig
#                deploymentconfig: docker-ispconfig
#            status:
#              loadBalancer: {}
#          kind: List
#          metadata: {}
#        token: "deployer-token-gj7xr"
#


#          apiVersion: "v1"
#          kind: "Pod"
#          metadata:
#            name: "ispconfig"
#            labels:
#              name: "ispconfig"
#          spec:
#            containers:
#              -
#                name: "ispconfig"
#                image: "{{ ose_project }}/{{ ispconfig_container }}"
#                ports:
#                  -
#                    containerPort: 80
#                    name: "ispconfig-http"
#                  -
#                    containerPort: 443
#                    name: "ispconfig-https"
#                  -
#                    containerPort: 20
#                    name: "ispconfig-ftp"
#                  -
#                    containerPort: 21
#                    name: "ispconfig-ftpd"
#                  -
#                    containerPort: 22
#                    name: "ispconfig-sshd"
#                  -
#                    containerPort: 953
#                    name: "ispconfig-secure-dns"
#                  -
#                    containerPort: 53
#                    name: "ispconfig-dns"
#                  -
#                    containerPort: 8080
#                    name: "ispconfig-admin"
#                  -
#                    containerPort: 3306
#                    name: "ispconfig-mysqld"
#                  -
#                    containerPort: 30000
#                    name: "ispconfig-comm0"
#                  -
#                    containerPort: 30001
#                    name: "ispconfig-comm1"
#                  -
#                    containerPort: 30002
#                    name: "ispconfig-comm2"
#                  -
#                    containerPort: 30003
#                    name: "ispconfig-comm3"
#                  -
#                    containerPort: 30004
#                    name: "ispconfig-comm4"
#                  -
#                    containerPort: 30005
#                    name: "ispconfig-comm5"
#                  -
#                    containerPort: 30006
#                    name: "ispconfig-comm6"
#                  -
#                    containerPort: 30007
#                    name: "ispconfig-comm7"
#                  -
#                    containerPort: 30008
#                    name: "ispconfig-comm8"
#                  -
#                    containerPort: 30009
#                    name: "ispconfig-comm9"
#
#                volumeMounts:
#                  -
#                    mountPath: "/var/www"
#                    name: "www"
#                  -
#                    mountPath: "/etc"
#                    name: "etc"
#                  -
#                    mountPath: "/var/mail"
#                    name: "mail"
#                  -
#                    mountPath: "/var/backup"
#                    name: "backup"
#                  -
#                    mountPath: "/var/lib/mysql"
#                    name: "mysql"
#                  -
#                    mountPath: "/usr/local/ispconfig"
#                    name: "data"
#                  -
#                    mountPath: "/var/log"
#                    name: "log"
#            volumes:
#              -
#                name: "www"
#                persistentVolumeClaim:
#                  claimName: "ispconfig-www"
#              -
#                name: "etc"
#                persistentVolumeClaim:
#                  claimName: "ispconfig-etc"
#              -
#                name: "mail"
#                persistentVolumeClaim:
#                  claimName: "ispconfig-mail"
#              -
#                name: "backup"
#                persistentVolumeClaim:
#                  claimName: "ispconfig-backup"
#              -
#                name: "mysql"
#                persistentVolumeClaim:
#                  claimName: "ispconfig-mysql"
#              -
#                name: "data"
#                persistentVolumeClaim:
#                  claimName: "ispconfig-data"
#              -
#                name: "log"
#                persistentVolumeClaim:
#                  claimName: "ispconfig-log"
#
#    - name: "Launch {{ ispconfig_container }} in openshift"
#      shell: |
#        oc login -u {{ ose_user }} -p {{ ose_pass }}
#        oc project {{ ose_project }}
#        oc new-app -i {{ ose_project }}/{{ ispconfig_container }}
#        echo "waiting 10 secs for it to deploy" && sleep 10
#      become: true
