---
- name: "Grab an OSE authorization token"
  hosts: all
  vars:
    ose_user: "admin"
    ose_pass: "redhat123"
    ose_project: Redhat_Lab
  tasks:
    - name: "Log into OSE"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }} -n {{ ose_project }}
        oc whoami -t
      register: token
      become: true
    
    - name: "Display OSE authorization token"
      debug: var=token
