---
- include: "ose-get-token.yml"
- name: "Launch ISPconfig"
  hosts: ose-cluster-master*
  vars:
    ose_project: "redhat-lab"
    ose_user: "admin"
    ose_pass: "redhat123"
    github_url: "https://github.com/syspimp/docker-ispconfig.git"
    ispconfig_container: "docker-ispconfig"
    mntpoints:
      - name: www
        mnt: /var/www
      - name: mail
        mnt: /var/mail
      - name: mysql
        mnt: /var/lib/mysql
      - name: backup
        mnt: /var/backup
      - name: data
        mnt: /usr/local/ispconfig
      - name: log
        mnt: /var/log
      - name: etc
        mnt: /etc
  tasks:
    - name: "create template for volume claims"
      template:
        src: ose/ispconfig-volume-claims.yml.j2
        dest: /tmp/ispconfig-volume-claims.yml
        mode: 0644
        owner: root
        group: root

    - name: "create template for volume"
      template:
        src: ose/ispconfig-volumes.yml.j2
        dest: /tmp/ispconfig-volumes.yml
        mode: 0644
        owner: root
        group: root

    - name: "Create persistent volume via oc binary"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        sed -e 's/REPLACEME/{{ item.name }}/' /tmp/ispconfig-volumes.yml | oc create -f -
      become: true
      with_items: "{{ mntpoints }}"

    - name: "Create volume claims via oc binary"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        sed -e 's/REPLACEME/{{ item.name }}/' /tmp/ispconfig-volume-claims.yml | oc create -f -
      become: true
      with_items: "{{ mntpoints }}"

    - name: "Have openshift create the application pods"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        oc new-app {{ github_url }}
      become: true

    - name: "Add volumes to the generated deploy config"
      shell: |
        oc login -u {{ ose_user }} -p {{ ose_pass }}
        oc project {{ ose_project }}
        oc volume dc/{{ ispconfig_container }} --add --name=ispconfig-{{ item.name }} \
        --type=persistentVolumeClaim \
        --claim-name=ispconfig-{{ item.name }} \
        --mount-path={{ item.mnt }}
      become: true
      with_items: "{{ mntpoints }}"
