---
- name: "Relaunch demos in OSP10"
  hosts: osp10-controllers
  gather_facts: no
  tasks:
    - name: "get list of vms off of osp10"
      shell: |
        source /root/keystonerc_dtaylor
        openstack server list | grep '|' | awk '{print $2}'|grep -v 'ID'
      become: true
      register: vms
      ignore_errors: yes

    - name: "get list of volumes off of osp10"
      shell: |
        source /root/keystonerc_dtaylor
        openstack volume list | grep '|' | awk '{print $2}'|grep -v 'ID'
      become: true
      register: volumes
      ignore_errors: yes

    - name: "delete all the vms off of osp10"
      shell: |
        source /root/keystonerc_dtaylor
        openstack server delete {{ item }}
        sleep 30
      become: true
      with_items: "{{ vms.stdout.split() }}"
      ignore_errors: yes

    - name: "delete all the volumes off of osp10"
      shell: |
        source /root/keystonerc_dtaylor
        openstack volume delete {{ item }}
        sleep 30
      become: true
      with_items: "{{ volumes.stdout.split() }}"
      ignore_errors: yes

    - name: "Pause for 5 minutes to let the volumes delete"
      pause:
        seconds: 300

    - name: "update all the ansible tower osp10 repos"
      shell: |
        curl --ciphers ecdhe_rsa_aes_128_gcm_sha_256 -f -k \
        -H 'Content-Type: application/json' -XPOST \
        --user admin:ansible \
        https://{{ default_tower_server }}/api/v1/inventory_sources/{{ item }}/update/
      with_items:
        - 226
        - 1141
        - 349
        - 310
        - 719
        - 720

    - name: "Launching demos"
      shell: |
        curl -f -k \
        -H 'Content-Type: application/json' -XPOST \
        --user admin:ansible \
        https://{{ default_tower_server }}:443/api/v1/job_templates/{{ item.id }}/launch/
        sleep 180
      with_items:
        - name: 'Satellite'
          id: '259'
        - name: 'CMFE'
          id: '260'
        - name: 'OSE 3.5'
          id: '258'
        - name: 'Tower'
          id: '294'
# this is too fast
#    - name: "Launching demos"
#      uri:
#        url: "https://{{ default_tower_server }}:443/api/v1/job_templates/{{ item.id }}/launch/"
#        validate_certs: no
#        method: POST
#        status_code: 201
#        user: admin
#        password: ansible
#        headers:
#          Content-Type: "application/json"
#      delay: 120
#      with_items:
#        - name: 'Satellite'
#          id: '259'
#        - name: 'CMFE'
#          id: '260'
#        - name: 'OSE 3.5'
#          id: '258'
#        - name: 'Tower'
#          id: '294'
