---
- name: "reset everything and rebuild environmnet"
  hosts: 10.55.102.158
  tasks:
    - name: "get list of vms off of osp10"
      shell: |
        source /root/keystonerc_dtaylor
        openstack server list | grep '|' | awk '{print $2}'|grep -v 'ID'
      become: true
      register: vms
      ignore_errors: yes

    - name: "delete all the vms off of osp10"
      shell: |
        source /root/keystonerc_dtaylor
        openstack server delete {{ item }}
        sleep 30
      become: true
      with_items: "{{ vms.stdout.split() }}"
      ignore_errors: yes

    - name: "update all the ansible tower osp10 repos"
      shell: |
        curl --ciphers ecdhe_rsa_aes_128_gcm_sha_256 -f -k \
        -H 'Content-Type: application/json' -XPOST \
        --user admin:ansible \
        https://10.55.102.248/api/v1/inventory_sources/{{ item }}/update/
        sleep 15
      with_items:
        - 226
        - 1141
        - 349
        - 310
        - 719
        - 720
      ignore_errors: yes
- include: reimage-servers.yml
