---
- include: "firstboot.yml"

- name: "Install Openstack 10 all in one"
  hosts: all
  tasks:
    - name: "Run Security Update Job"
      shell: "curl -k --data 'host_config_key={{ redhat_insights_key }}' https://{{ host_config_server }}:443/api/v1/job_templates/{{ redhat_insights_jobid }}/callback/"

    - name: "Enabling needed repos for Openstack 10"
      shell: "subscription-manager repos --enable={{ item }}"
      with_items: "{{ openstack_enabled_repos }}"
      become: true
    
    - name: "Install Openstack 10 Yum packages"
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ openstack_packages }}"
      become: true

    - name: "apply fix for packstack bugzilla 1147811 part 1"
      lineinfile:
        - path: /usr/share/openstack-puppet/modules/packstack/manifests/nova/compute.pp
          state: present
          regexp: "^'libvirt/live_migration_uri':$"
          line: "#'libvirt/live_migration_uri':"

    - name: "apply fix for packstack bugzilla 1147811 part 2"
      lineinfile:
        - path: /usr/share/openstack-puppet/modules/packstack/manifests/nova/compute.pp
          state: present
          regexp: "^value => hiera('CONFIG_NOVA_COMPUTE_MIGRATE_URL');$"
          line: "#value => hiera('CONFIG_NOVA_COMPUTE_MIGRATE_URL');"

    - name: "Run packstack --allinone"
      shell: "packstack --allinone"
      become: true
