---
#- include: "control-rack-power.yml"

- name: "Enable OSP 10 repos on all hosts"
  hosts: 10.55.102.158,10.55.102.157,10.55.102.156
  tasks:
    - name: "Enabling needed repos for Openstack 10"
      shell: "subscription-manager repos --enable={{ item }}"
      with_items: "{{ openstack_enabled_repos }}"
      become: true

- name: "Install Openstack 10 all in one"
  hosts: 10.55.102.158
  tasks:
    - name: "installing private key"
      template:
        src: openstack/blank.key.j2
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600

    - name: "copying authorized key to id_rsa.pub"
      shell: |
        cp /root/.ssh/authorized_keys /root/.ssh/id_rsa.pub

    - name: "Install Openstack 10 Yum packages"
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ openstack_packages }}"
      become: true

    - name: "apply fix for packstack bugzilla 1147811"
      template:
        src: openstack/compute.pp.j2
        dest: /usr/share/openstack-puppet/modules/packstack/manifests/nova/compute.pp
        owner: root
        group: root
        mode: 0644

    - name: "copy over pre-generated answer file"
      template:
        src: openstack/packstack-answer.txt.j2
        dest: /root/packstack-answer.txt
        owner: root
        group: root
        mode: 0644

    - name: "Add cinder-volumes vol group"
      shell: |
        echo "n
        p
        
        
        
        t
        
        8e
        w
        "|fdisk /dev/sda
        partprobe
        vgcreate cinder-volumes /dev/sda3
      ignore_errors: yes
      become: true

    - name: "Run packstack against answer file"
      shell: "packstack --answer-file=/root/packstack-answer.txt"
      become: true
#      when: os_packstack_use_answerfile == "yes"
#
#    ## for demo use
#    - name: "Run packstack --allinone"
#      shell: "packstack --allinone"
#      become: true
#      when: os_packstack_use_answerfile == "no"

## customize openstack
- include: "openstack-glance-import.yml"

