---
#- include: "control-rack-power.yml"

- name: "Enable OSP 10 repos on all hosts"
  hosts: osp10-nodes
  tasks:
    - name: "Enabling needed repos for Openstack 10"
      shell: "subscription-manager repos --enable={{ item }}"
      become: true
      with_items:
        - rhel-7-server-openstack-10-rpms
        - rhel-7-server-rh-common-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-openstack-10-devtools-rpms

- name: "Install Openstack 10 on 3 nodes"
  hosts: osp10-controllers
  vars:
    os_packstack_use_answerfile: "yes"
    os_controller_nodes: "{{ osp10_controller }}"
    os_compute_nodes: "{{ osp10_computes }}"
    os_network_nodes: "{{ osp10_controller }}"
    os_storage_node: "{{ osp10_controller }}"
    os_cinder_volumesgroup_size: "1000G"
    os_amqp_nodes: "{{ osp10_controller }}"
    os_mariadb_nodes: "{{ osp10_controller }}"
    #os_cinder_device: "/dev/sda"
    os_cinder_device: "/dev/sda1"
    os_swift_device: "/dev/sda2"
    ml2_drivers: "local,vlan"
    ml2_networks: "local,vlan"
    ml2_bridge_name: "inter-vlan"
    ml2_vlan_ranges: "2:120"
    ovs_bridged_interface: "enp10s0f1"
  tasks:
    - name: "installing private key"
      template:
        src: openstack/blank.key.j2
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600

    - name: "copying authorized key to id_rsa.pub"
      shell: |
        cp /root/.ssh/authorized_keys /root/.ssh/id_rsa.pub

    - name: "Install Openstack 10 Yum packages"
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ openstack_packages }}"
      become: true

#    - name: "apply fix for packstack bugzilla 1147811"
#      template:
#        src: openstack/compute.pp.j2
#        dest: /usr/share/openstack-puppet/modules/packstack/manifests/nova/compute.pp
#        owner: root
#        group: root
#        mode: 0644

    - name: "copy over pre-generated answer file"
      template:
        src: openstack/packstack-answer.txt.j2
        dest: /root/packstack-answer.txt
        owner: root
        group: root
        mode: 0644

    - name: "Check if cinder-volume exists"
      shell: "vgdisplay | grep cinder || true"
      register: cinder
      ignore_errors: yes

    - name: "Add cinder-volumes vol group"
      shell: |
        echo "n
        p
        
        
        
        t
        
        8e
        w
        "|fdisk /dev/sda
        partprobe
        vgcreate cinder-volumes /dev/sda3
      ignore_errors: yes
      become: true
      when: "'cinder' not in cinder.stdout"

    - name: "Run packstack against answer file - takes 55 mins for 3 nodes"
      shell: "packstack --answer-file=/root/packstack-answer.txt"
      become: true
      when: os_packstack_use_answerfile == "yes"

    - name: "Run packstack --allinone for demo on a single server"
      shell: "packstack --allinone"
      become: true
      when: os_packstack_use_answerfile == "no"

## customize openstack
- include: "configure-osp10.yml"
