---
- name: Firstboot configuration tasks
  hosts: all:!satellite*:!cfme*:!cloudforms*
  roles:
    - firstboot

- name: Install Jboss Standalone
  hosts: jboss*
  roles:
    - jboss-standalone

- name: Configure Satellite
  hosts: satellite*
  roles:
    - satellite-server

- name: Configure Cloudforms Management Engine
  hosts: cloudforms*:cfme*
  roles:
    - cloudforms-server

- name: Configure Openstack Compute Nodes with HugePages, CPU pinning 
  hosts: osp10-computes
  roles:
    - { role: openstack, osp_mode: computes }

- name: Customize Openstack -  create networks, projects, users, and import glance images from nfs share
  hosts: osp10-controllers
  roles:
    - { role: openstack, osp_mode: controllers, cfme: true }

- name: Customize Openshift Container Platform nodes
  hosts: ose-cluster-node-1.dev.maskedadmins.com,ose-cluster-node-2.dev.maskedadmins.com
  roles:
    - { role: openshift, ocp_mode: nodes }

- name: Customize Openshift Container Platform with 2 additional nodes
  hosts: ose-cluster-master.dev.maskedadmins.com
  roles:
    - { role: openshift, ocp_mode: controllers, cfme: true }

- name: Customize Ansible Tower
  hosts: tower*
  roles:
    - ansible-tower
