---
- name: Firstboot configuration tasks
  hosts: all:!cfme*:!cloudforms*
  become: yes
  roles:
    - firstboot
    - insights

- name: Install Jboss Standalone
  hosts: jboss*
  become: yes
  roles:
    - jboss-standalone

- name: Configure Satellite
  hosts: sat6*
  roles:
    - satellite-server

- name: Configure Cloudforms Management Engine
  hosts: cloudforms*:cfme*
  roles:
    - cloudforms-server
    - firstboot
    - insights

#- name: Configure Openstack Compute Nodes with HugePages, CPU pinning 
#  hosts: osp10-computes
#  roles:
#    - { role: openstack, osp_mode: computes, cfme: false }

#- name: Customize Openstack -  create networks, projects, users, and import glance images from nfs share
#  hosts: osp10-controllers
#  roles:
#    - { role: openstack, osp_mode: controllers, cfme: true }

- name: Customize Openshift Container Platform nodes
  hosts: ose-cluster-node-1.dev.maskedadmins.com,ose-cluster-node-2.dev.maskedadmins.com
  roles:
    - { role: openshift, ocp_mode: nodes, cfme: false }

- name: Customize Openshift Container Platform with 2 additional nodes
  hosts: ose-cluster-master.dev.maskedadmins.com
  roles:
    - { role: openshift, ocp_mode: controllers, cfme: true }

- name: Customize Ansible Tower
  hosts: tower*:10.55.102.156
  roles:
    - ansible-tower
