---
- hosts: localhost
  name: test
  vars:
    list_of_instanceids: []
    action: "goodmorning"
  tasks:

    - name: see what is available to filter
      debug: var=hostvars[item]
      with_inventory_hostnames: all

    - name: filter ec2 instances from inventory
      debug: var=hostvars[item]['ec2_ip_address']
      when: "hostvars[item]['instance-id'] is defined"
      with_inventory_hostnames: all

    - name: filter ec2 instances from inventory
      set_fact: "{{ list_of_instanceids }} + [ '{{ hostvars[item]['instance-id'] }}' ]"
      when: "hostvars[item]['instance-id'] is defined"
      with_inventory_hostnames: all

    - name: make sure the instances are running
      ec2_instance:
        state: running
        instance_ids: "{{ list_of_instanceids }}"
      when: action == 'goodmorning' and hostvars[item]['instance-id'] is defined
      with_inventory_hostnames: all

    - name: make sure the instances are stopped
      ec2_instance:
        state: stopped
        instance_ids: "{{ list_of_instanceids }}"
      when: action == 'goodnight' and hostvars[item]['instance-id'] is defined
      with_inventory_hostnames: all
