---
- hosts: localhost
  name: test
  vars:
    action: "goodmorning"
    ocp_clustername: redhatlab
  tasks:
    #use this if you forget your encrypted aws creds
    - name: "AWS_ACCESS_KEY_ID"
      debug: var=AWS_ACCESS_KEY_ID
    - name: "AWS_SECRET_KEY"
      debug: var=AWS_SECRET_KEY

    - name: filter ec2 instances from inventory
      debug: var=hostvars[item]['ec2_ip_address']
      when: "hostvars[item]['ec2_id'] is defined"
      with_inventory_hostnames: all

    - name: grab all ocp clusters
      ec2_instance_facts:
        region: "{{ aws_region }}"
        filters:
          instance-state-name: [ "running","shutting-down", "stopping", "stopped" ]
          #"tag:Name": redhatlab
      register: findocp

    - name: dump ec2 results
      debug: var=findocp
      #debug: var=item.tags.Name
      #when: "ocp_clustername is in item.tags.Name"
      #loop: findocp
      
    - name: filter ec2 instances from inventory
      set_fact:
        list_of_instanceids: "{{ list_of_instanceids | default([],True) }} + [ '{{ hostvars[item]['ec2_id'] }}' ]"
      when: "hostvars[item]['ec2_id'] is defined"
      with_inventory_hostnames: all

    - name: dump list of instanceids
      debug: var=list_of_instanceids

    - name: make sure the instances are running
      ec2_instance:
        state: running
        instance_ids: "{{ list_of_instanceids }}"
        region: "{{ aws_region }}"
      when: action == 'goodmorning' and list_of_instanceids | length >= 1

    - name: make sure the instances are stopped
      ec2_instance:
        state: stopped
        instance_ids: "{{ list_of_instanceids }}"
        region: "{{ aws_region }}"
      when: action == 'goodnight' and list_of_instanceids | length >= 1
