---
- hosts: localhost
  name: test
  tasks:

    - name: see what is available to filter
      debug: var=hostvars[item]
      with_inventory_hostnames: all

    - name: filter ec2 instances from inventory
      debug: var=hostvars[item]['ec2_ip_address']
      when: "hostvars[item]['ec2_tag_Name'] is defined"
      with_inventory_hostnames: all
