---
- hosts: localhost
  name: test
  vars:
    action: "goodmorning"
    list_of_instanceids: []
  tasks:

#    - name: see what is available to filter
#      debug: var=hostvars[item]
#      with_inventory_hostnames: all

    - name: filter ec2 instances from inventory
      debug: var=hostvars[item]['ec2_ip_address']
      when: "hostvars[item]['ec2_id'] is defined"
      with_inventory_hostnames: all

    - name: filter ec2 instances from inventory
      #set_fact: "[ '{{ hostvars[item]['ec2_id'] }}' ]"
      set_fact:
        list_of_instanceids: "{{ list_of_instanceids | default([],True) }} + [ '{{ hostvars[item]['ec2_id'] }}' ]"
      when: "hostvars[item]['ec2_id'] is defined"
      with_inventory_hostnames: all

    - name: dump list of instanceids
      debug: var=list_of_instanceids

    - name: make sure the instances are running
      ec2_instance:
        state: running
        instance_ids: "{{ list_of_instanceids }}"
        region: "{{ aws_region }}"
      #when: action == 'goodmorning' and hostvars[item]['ec2_id'] is defined
      when: action == 'goodmorning' and list_of_instanceids | length >= 1
      #with_inventory_hostnames: all

    - name: make sure the instances are stopped
      ec2_instance:
        state: stopped
        ec2_ids: "{{ list_of_instanceids }}"
      when: action == 'goodnight'
