---
- hosts: localhost
  name: test
  tasks:

    - name: dump loop item
      debug: var=itm
      with_inventory_hostnames: all

    - name: grab ec2 instances from inventory
      debug: var=hostvars[item]['host_config_server']
      #when: "hostvars[item]['ansible_facts']['ansible_system_vendor'] is defined and 'Amazon EC2' in hostvars[item]['ansible_facts']['ansible_system_vendor']"
      with_inventory_hostnames: all
